import { NoteItem, PYQItem, SyllabusSubject, PlaylistCard, ShortNoteItem, SubjectBox } from "@/types";
import { csBtechSubjects } from "./btech-cs";
import { allCurriculums } from "./curriculum";
export { allCurriculums };

export const COURSES_BY_LEVEL = {
  UG: [
    "B.Tech Computer Science",
    "B.Tech Electronics & Comm",
    "B.Tech Mechanical Eng",
    "B.Tech Civil Engineering",
    "B.Tech Electrical & Electronics",
    "B.Tech Information Technology",
    "B.Tech AI & Data Science",
    "B.Tech Automobile Engineering",
    "B.Sc Computer Science",
    "B.Sc Physics",
    "BCA (Computer Applications) - MGU",
    "B.Com Business Administration",
    "BBA Marketing & Mgmt",
  ],
  PG: [
    "M.Tech Computer Science & AI",
    "M.Tech Embedded Systems",
    "M.Sc Data Science",
    "M.Sc Physics & Electronics",
    "MCA (Master of Computer Apps)",
    "MBA Finance & Systems",
  ],
};

export const mockNotes: NoteItem[] = [
  {
    id: "note-1",
    title: "Data Structures & Algorithms Comprehensive Guide",
    subject: "Data Structures",
    pages: 42,
    lastOpened: "Today",
    author: "Prof. R. K. Sharma",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "UG",
    course: "B.Tech Computer Science",
    summary: "Covers Arrays, Linked Lists, Trees, Graphs, Sorting, Dynamic Programming & Time Complexity Analysis.",
  },
  {
    id: "note-2",
    title: "Operating Systems — Process Scheduling & Synchronization",
    subject: "Operating Systems",
    pages: 28,
    lastOpened: "2 days ago",
    author: "Dr. Ananya Roy",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "UG",
    course: "B.Tech Computer Science",
    summary: "Detailed notes on CPU Scheduling algorithms, Semaphores, Deadlocks, Virtual Memory & Page Replacement.",
  },
  {
    id: "note-3",
    title: "Thermodynamics & Heat Transfer Unit 1-4",
    subject: "Thermodynamics",
    pages: 35,
    lastOpened: "Yesterday",
    author: "Prof. S. V. Nair",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "UG",
    course: "B.Tech Mechanical Eng",
    summary: "Laws of Thermodynamics, Enthalpy, Carnot Engine, Entropy and Refrigeration Cycles.",
  },
  {
    id: "note-4",
    title: "Advanced Machine Learning & Neural Networks",
    subject: "Machine Learning",
    pages: 56,
    lastOpened: "3 days ago",
    author: "Dr. K. Mehta",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "PG",
    course: "M.Tech Computer Science & AI",
    summary: "Deep Neural Nets, CNNs, RNNs, Transformer architectures, Backpropagation calculus & PyTorch code samples.",
  },
  {
    id: "note-5",
    title: "Database Management Systems (SQL & NoSQL)",
    subject: "DBMS",
    pages: 31,
    lastOpened: "5 days ago",
    author: "Prof. V. Gupta",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "UG",
    course: "BCA (Computer Applications) - MGU",
    summary: "Relational Algebra, ER Diagrams, Normalization (1NF to BCNF), SQL Queries & MongoDB basics.",
  },
  {
    id: "note-6",
    title: "Quantum Mechanics & Wave Functions",
    subject: "Physics",
    pages: 24,
    lastOpened: "1 week ago",
    author: "Dr. P. Deshmukh",
    url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
    level: "UG",
    course: "B.Sc Physics",
    summary: "Schrödinger wave equations, Particle in a box, Wave-particle duality & Quantum operators.",
  },
];

export const mockPYQs: PYQItem[] = [
  {
    id: "pyq-1",
    year: "2024",
    subject: "Data Structures",
    examType: "Final",
    url: "#",
    course: "B.Tech Computer Science",
    level: "UG",
    hasSolution: true,
  },
  {
    id: "pyq-2",
    year: "2023",
    subject: "Data Structures",
    examType: "Midterm",
    url: "#",
    course: "B.Tech Computer Science",
    level: "UG",
    hasSolution: true,
  },
  {
    id: "pyq-3",
    year: "2023",
    subject: "Operating Systems",
    examType: "Final",
    url: "#",
    course: "B.Tech Computer Science",
    level: "UG",
    hasSolution: true,
  },
  {
    id: "pyq-4",
    year: "2022",
    subject: "Computer Networks",
    examType: "Midterm",
    url: "#",
    course: "B.Tech Computer Science",
    level: "UG",
    hasSolution: false,
  },
  {
    id: "pyq-5",
    year: "2024",
    subject: "Machine Learning",
    examType: "Final",
    url: "#",
    course: "M.Tech Computer Science & AI",
    level: "PG",
    hasSolution: true,
  },
  {
    id: "pyq-6",
    year: "2023",
    subject: "Thermodynamics",
    examType: "Final",
    url: "#",
    course: "B.Tech Mechanical Eng",
    level: "UG",
    hasSolution: true,
  },
];

export const mockSyllabus: SyllabusSubject[] = [
  {
    id: "sub-1",
    subject: "Data Structures & Algorithms",
    code: "CS401",
    course: "B.Tech Computer Science",
    level: "UG",
    progress: 60,
    units: [
      {
        id: "u1-1",
        title: "Unit 1: Linear Data Structures",
        topics: [
          { id: "t-1", title: "Arrays, Memory Representation & Operations", completed: true },
          { id: "t-2", title: "Singly and Doubly Linked Lists", completed: true },
          { id: "t-3", title: "Stacks Application & Expression Evaluation", completed: true },
          { id: "t-4", title: "Queues & Circular Queue Implementations", completed: true },
        ],
      },
      {
        id: "u1-2",
        title: "Unit 2: Trees & Hierarchical Structures",
        topics: [
          { id: "t-5", title: "Binary Trees & Traversal Techniques (In/Pre/Post)", completed: true },
          { id: "t-6", title: "Binary Search Trees (BST) Insertion & Deletion", completed: false },
          { id: "t-7", title: "AVL Trees & Rotations", completed: false },
          { id: "t-8", title: "Heaps & Priority Queues", completed: false },
        ],
      },
      {
        id: "u1-3",
        title: "Unit 3: Graphs & Shortest Paths",
        topics: [
          { id: "t-9", title: "Graph Representation (Adjacency Matrix & List)", completed: false },
          { id: "t-10", title: "BFS and DFS Traversal Algorithms", completed: false },
          { id: "t-11", title: "Dijkstra's Algorithm & Prim's MST", completed: false },
        ],
      },
    ],
  },
  {
    id: "sub-2",
    subject: "Operating Systems",
    code: "CS402",
    course: "B.Tech Computer Science",
    level: "UG",
    progress: 40,
    units: [
      {
        id: "u2-1",
        title: "Unit 1: Process Management & CPU Scheduling",
        topics: [
          { id: "t-12", title: "Process State Lifecycle & PCB", completed: true },
          { id: "t-13", title: "FCFS, SJF, Round Robin & Priority Scheduling", completed: true },
          { id: "t-14", title: "Inter-process Communication (IPC)", completed: false },
        ],
      },
      {
        id: "u2-2",
        title: "Unit 2: Memory Management",
        topics: [
          { id: "t-15", title: "Paging & Segmentation Concepts", completed: false },
          { id: "t-16", title: "Virtual Memory & Page Fault Handling", completed: false },
          { id: "t-17", title: "LRU, FIFO & Optimal Page Replacement", completed: false },
        ],
      },
    ],
  },
  {
    id: "sub-3",
    subject: "Advanced Machine Learning",
    code: "AI601",
    course: "M.Tech Computer Science & AI",
    level: "PG",
    progress: 75,
    units: [
      {
        id: "u3-1",
        title: "Unit 1: Supervised Learning & Deep Neural Nets",
        topics: [
          { id: "t-18", title: "Multilayer Perceptrons & Activation Functions", completed: true },
          { id: "t-19", title: "Gradient Descent Variants (Adam, RMSProp)", completed: true },
          { id: "t-20", title: "Regularization (Dropout, L1/L2)", completed: true },
        ],
      },
    ],
  },
];

export const mockPlaylists: PlaylistCard[] = [
  {
    id: "play-1",
    title: "Data Structures & Algorithms in C++ / Java (Full Course)",
    subject: "Data Structures",
    channelName: "GATE Smashers / mycodeschool",
    videoCount: 45,
    thumbnail: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?w=600&auto=format&fit=crop&q=80",
    embedId: "8hly31xKLI0", // Standard DS tutorial
    course: "B.Tech Computer Science",
    level: "UG",
    durationHours: 24,
  },
  {
    id: "play-2",
    title: "Operating Systems Complete Playlist for Exams",
    subject: "Operating Systems",
    channelName: "Knowledge Gate / Neso Academy",
    videoCount: 32,
    thumbnail: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?w=600&auto=format&fit=crop&q=80",
    embedId: "bkSWJJZNgf8",
    course: "B.Tech Computer Science",
    level: "UG",
    durationHours: 18,
  },
  {
    id: "play-3",
    title: "DBMS Complete Course (SQL, ER Diagram, Normalization)",
    subject: "DBMS",
    channelName: "CodeWithHarry / Jenny's Lectures",
    videoCount: 28,
    thumbnail: "https://images.unsplash.com/photo-1544383835-bda2bc66a55d?w=600&auto=format&fit=crop&q=80",
    embedId: "3EJOX2kGyVU",
    course: "B.Tech Computer Science",
    level: "UG",
    durationHours: 15,
  },
  {
    id: "play-4",
    title: "Deep Learning & Neural Networks Masterclass",
    subject: "Machine Learning",
    channelName: "DeepLearning.AI / Krish Naik",
    videoCount: 50,
    thumbnail: "https://images.unsplash.com/photo-1555949963-ff9fe0c870eb?w=600&auto=format&fit=crop&q=80",
    embedId: "aircAruvnKk",
    course: "M.Tech Computer Science & AI",
    level: "PG",
    durationHours: 35,
  },
  {
    id: "play-5",
    title: "Engineering Thermodynamics & Heat Engine Lectures",
    subject: "Thermodynamics",
    channelName: "NPTEL / Learn Engineering",
    videoCount: 22,
    thumbnail: "https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=600&auto=format&fit=crop&q=80",
    embedId: "9GMBpZZtjrc",
    course: "B.Tech Mechanical Eng",
    level: "UG",
    durationHours: 14,
  },
];

export const mockShortNotes: ShortNoteItem[] = [
  {
    id: "sn-1",
    title: "Time & Space Complexities Cheat Sheet",
    subject: "Data Structures",
    readTime: "3 min read",
    course: "B.Tech Computer Science",
    level: "UG",
    keyPoints: [
      "Binary Search Tree: Average O(log N), Worst O(N)",
      "Quick Sort: Average O(N log N), Worst O(N^2) when array is sorted",
      "Merge Sort: Stable algorithm with guaranteed O(N log N) space O(N)",
      "Hash Table Insertion & Lookup: Average O(1), Worst O(N) on collisions",
    ],
    formula: "Master Theorem: T(n) = a T(n/b) + f(n)",
  },
  {
    id: "sn-2",
    title: "CPU Scheduling Formulas & Key Rules",
    subject: "Operating Systems",
    readTime: "4 min read",
    course: "B.Tech Computer Science",
    level: "UG",
    keyPoints: [
      "Turnaround Time (TAT) = Completion Time - Arrival Time",
      "Waiting Time (WT) = Turnaround Time - Burst Time",
      "Response Time = First CPU Allocation Time - Arrival Time",
      "SJF guarantees minimum average waiting time among non-preemptive schedulers",
    ],
    formula: "TAT = CT - AT | WT = TAT - BT",
  },
  {
    id: "sn-3",
    title: "Database Normalization Quick Rules (1NF to BCNF)",
    subject: "DBMS",
    readTime: "5 min read",
    course: "B.Tech Computer Science",
    level: "UG",
    keyPoints: [
      "1NF: Atomic values only in attributes",
      "2NF: In 1NF + No Partial Dependencies (non-prime depends on full candidate key)",
      "3NF: In 2NF + No Transitive Dependencies (non-prime -> non-prime)",
      "BCNF: For every FD X -> Y, X must be a super key",
    ],
  },
  {
    id: "sn-4",
    title: "Laws of Thermodynamics & Carnot Efficiency Formula",
    subject: "Thermodynamics",
    readTime: "3 min read",
    course: "B.Tech Mechanical Eng",
    level: "UG",
    keyPoints: [
      "Zeroth Law: Thermal equilibrium establishes temperature concept",
      "First Law: Energy conservation (dQ = dU + dW)",
      "Second Law: Heat flows spontaneously from hot to cold; Entropy of isolated system increases",
    ],
    formula: "Carnot Efficiency η = 1 - (Tc / Th)",
  },
];

export const mockSubjectBoxes: SubjectBox[] = [
  {
    id: "sb-1",
    subjectName: "Data Structures & Algorithms",
    code: "CS401",
    description: "Core algorithms, data abstractions, time complexity analysis, trees, graphs, and dynamic programming.",
    course: "B.Tech Computer Science",
    level: "UG",
    semester: 3,
    chapters: [
      {
        id: "ch-dsa-1",
        chapterNumber: 1,
        title: "Arrays, Memory Allocation & Linked Lists",
        description: "Static arrays, dynamic arrays, contiguous memory allocation, singly and doubly linked list operations.",
        notes: [
          {
            id: "note-dsa-101",
            order: 1,
            title: "01. Introduction to Arrays & Memory Layout",
            summary: "Detailed overview of one-dimensional and multi-dimensional array memory mapping, row-major vs column-major order, and index calculations.",
            pages: 18,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-01",
          },
          {
            id: "note-dsa-102",
            order: 2,
            title: "02. Singly Linked Lists — Operations & Code Walkthrough",
            summary: "Step-by-step algorithms for insertion at head/tail/k-th position, deletion, reversing linked list iteratively and recursively.",
            pages: 24,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-03",
          },
          {
            id: "note-dsa-103",
            order: 3,
            title: "03. Doubly & Circular Linked Lists",
            summary: "Comprehensive comparison between singly, doubly, and circular linked lists with pointer manipulation edge cases.",
            pages: 16,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-04",
          },
        ],
      },
      {
        id: "ch-dsa-2",
        chapterNumber: 2,
        title: "Stacks, Queues & Expression Evaluation",
        description: "LIFO and FIFO data structures, array and linked list implementations, infix, prefix, and postfix conversions.",
        notes: [
          {
            id: "note-dsa-201",
            order: 1,
            title: "01. Stack ADT & Infix to Postfix Conversion",
            summary: "Stack operations (push, pop, peek), operator precedence rules, shunting-yard algorithm, and postfix expression evaluation.",
            pages: 20,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-05",
          },
          {
            id: "note-dsa-202",
            order: 2,
            title: "02. Queue ADT, Circular Queue & Deque",
            summary: "Fixing array queue overflow via circular buffer representation, double-ended queue (Deque), and real-world CPU task queues.",
            pages: 22,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-06",
          },
        ],
      },
      {
        id: "ch-dsa-3",
        chapterNumber: 3,
        title: "Trees, BST & Balanced Search Trees",
        description: "Hierarchical data representation, tree traversals, binary search tree insertions, deletions, and self-balancing AVL trees.",
        notes: [
          {
            id: "note-dsa-301",
            order: 1,
            title: "01. Binary Tree Traversals (Inorder, Preorder, Postorder)",
            summary: "Recursive vs iterative depth-first tree traversals, level-order traversal using queue, and tree construction from preorder+inorder.",
            pages: 30,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-07",
          },
          {
            id: "note-dsa-302",
            order: 2,
            title: "02. Binary Search Trees (BST) & AVL Balancing Rotations",
            summary: "BST search/insert/delete algorithms, balance factor, single (LL/RR) and double (LR/RL) AVL rotations.",
            pages: 36,
            author: "Dr. K. Mehta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-08",
          },
        ],
      },
      {
        id: "ch-dsa-4",
        chapterNumber: 4,
        title: "Graphs, Shortest Paths & Dynamic Programming",
        description: "Adjacency matrix vs list representation, BFS, DFS, Dijkstra's algorithm, Prim's MST, and dynamic programming fundamentals.",
        notes: [
          {
            id: "note-dsa-401",
            order: 1,
            title: "01. Graph Representations, BFS & DFS Algorithms",
            summary: "Space & time trade-offs between adjacency matrices and lists, graph traversal algorithms, connected components & cycle detection.",
            pages: 28,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-08",
          },
          {
            id: "note-dsa-402",
            order: 2,
            title: "02. Dijkstra's Shortest Path & Prim's Minimum Spanning Tree",
            summary: "Greedy algorithms on weighted graphs, min-heap priority queue optimizations, and step-by-step trace tables.",
            pages: 32,
            author: "Dr. K. Mehta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-09",
          },
          {
            id: "note-dsa-403",
            order: 3,
            title: "03. Dynamic Programming — 0/1 Knapsack & LCS",
            summary: "Overlapping subproblems, optimal substructure, memoization vs bottom-up tabulation tables, and classic DP problems.",
            pages: 38,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-09",
          },
        ],
      },
    ],
  },
  {
    id: "sb-2",
    subjectName: "Operating Systems",
    code: "CS402",
    description: "System calls, process scheduling, CPU dispatching, concurrency control, semaphores, memory management, and paging.",
    course: "B.Tech Computer Science",
    level: "UG",
    semester: 4,
    chapters: [
      {
        id: "ch-os-1",
        chapterNumber: 1,
        title: "Process Management & CPU Scheduling",
        description: "Process lifecycle, PCB structures, context switching, CPU scheduling metrics, FCFS, SJF, and Round-Robin.",
        notes: [
          {
            id: "note-os-101",
            order: 1,
            title: "01. Process Concept, PCB & System Calls",
            summary: "Process states (New, Ready, Running, Waiting, Terminated), Process Control Block fields, fork() exec() system call mechanics.",
            pages: 22,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-02",
          },
          {
            id: "note-os-102",
            order: 2,
            title: "02. CPU Scheduling Algorithms (FCFS, SJF, RR, Priority)",
            summary: "Calculation of Turnaround Time (TAT) and Waiting Time (WT), Gantt chart construction, preemptive vs non-preemptive scheduling.",
            pages: 28,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-04",
          },
        ],
      },
      {
        id: "ch-os-2",
        chapterNumber: 2,
        title: "Process Synchronization & Deadlocks",
        description: "Critical section problem, Peterson's solution, mutex locks, semaphores, Producer-Consumer problem, and Banker's algorithm.",
        notes: [
          {
            id: "note-os-201",
            order: 1,
            title: "01. Critical Section, Mutex & Counting Semaphores",
            summary: "Mutual exclusion, progress, bounded waiting criteria, wait() and signal() semaphore primitives, classic synchronization problems.",
            pages: 26,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-05",
          },
          {
            id: "note-os-202",
            order: 2,
            title: "02. Deadlock Characterization & Banker's Algorithm",
            summary: "Four necessary deadlock conditions, Resource Allocation Graph (RAG), Banker's safety and resource request algorithms.",
            pages: 30,
            author: "Prof. S. V. Nair",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-07",
          },
        ],
      },
      {
        id: "ch-os-3",
        chapterNumber: 3,
        title: "Memory Management & Page Replacement",
        description: "Logical vs physical address spaces, paging hardware, Translation Lookaside Buffer (TLB), page fault handling, LRU, and FIFO.",
        notes: [
          {
            id: "note-os-301",
            order: 1,
            title: "01. Paging Architecture & TLB Hardware",
            summary: "Page table entry structures, multi-level paging, effective memory access time calculations with TLB hit ratios.",
            pages: 25,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-08",
          },
          {
            id: "note-os-302",
            order: 2,
            title: "02. Virtual Memory & Page Replacement Algorithms",
            summary: "Demand paging, page fault service routines, FIFO, Optimal, and Least Recently Used (LRU) page replacement calculations.",
            pages: 32,
            author: "Dr. Ananya Roy",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-09",
          },
        ],
      },
    ],
  },
  {
    id: "sb-3",
    subjectName: "Database Management Systems (DBMS)",
    code: "CS403",
    description: "Relational data model, ER diagrams, SQL queries, relational algebra, database normalization (1NF to BCNF), and ACID transactions.",
    course: "B.Tech Computer Science",
    level: "UG",
    semester: 4,
    chapters: [
      {
        id: "ch-dbms-1",
        chapterNumber: 1,
        title: "Relational Model & ER Diagrams",
        description: "Entities, attributes, relationships, cardinality constraints, ER to Relational schema mapping, and primary/foreign keys.",
        notes: [
          {
            id: "note-dbms-101",
            order: 1,
            title: "01. ER Modeling & Relational Schema Design",
            summary: "Constructing ER diagrams, identifying strong vs weak entities, participation constraints, and translating ER graphs to SQL tables.",
            pages: 20,
            author: "Prof. V. Gupta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-03",
          },
          {
            id: "note-dbms-102",
            order: 2,
            title: "02. Relational Algebra Operations",
            summary: "Select, Project, Cartesian Product, Natural Join, Outer Joins, Division operator, and algebraic query optimization.",
            pages: 24,
            author: "Prof. V. Gupta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-05",
          },
        ],
      },
      {
        id: "ch-dbms-2",
        chapterNumber: 2,
        title: "SQL & Database Normalization",
        description: "Structured Query Language, DDL, DML, GROUP BY, HAVING, subqueries, functional dependencies, 1NF, 2NF, 3NF, and BCNF.",
        notes: [
          {
            id: "note-dbms-201",
            order: 1,
            title: "01. Advanced SQL Queries & Joins",
            summary: "Writing complex multi-table JOINs, subqueries, correlated subqueries, aggregate functions, and index creation.",
            pages: 28,
            author: "Prof. V. Gupta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-06",
          },
          {
            id: "note-dbms-202",
            order: 2,
            title: "02. Functional Dependencies & Normal Forms (1NF - BCNF)",
            summary: "Attribute closure algorithms, candidate key identification, testing losslessness and dependency preservation during decomposition.",
            pages: 34,
            author: "Prof. V. Gupta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-08",
          },
        ],
      },
    ],
  },
  {
    id: "sb-4",
    subjectName: "Computer Networks",
    code: "CS404",
    description: "OSI & TCP/IP layers, IP addressing, subnetting, TCP/UDP transport mechanics, routing protocols, HTTP, and DNS.",
    course: "B.Tech Computer Science",
    level: "UG",
    semester: 4,
    chapters: [
      {
        id: "ch-cn-1",
        chapterNumber: 1,
        title: "Network Architectures & Physical/Data Link Layer",
        description: "OSI 7-layer vs TCP/IP 4-layer model, framing, error detection (CRC), CSMA/CD, and Ethernet switching.",
        notes: [
          {
            id: "note-cn-101",
            order: 1,
            title: "01. OSI Reference Model & Protocol Layers",
            summary: "Functions of Physical, Data Link, Network, Transport, Session, Presentation, and Application layers with encapsulation flow.",
            pages: 21,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-01",
          },
          {
            id: "note-cn-102",
            order: 2,
            title: "02. Error Detection, Framing & Sliding Window Protocols",
            summary: "Cyclic Redundancy Check (CRC) polynomial division, Stop-and-Wait, Go-Back-N, and Selective Repeat ARQ protocols.",
            pages: 27,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-04",
          },
        ],
      },
      {
        id: "ch-cn-2",
        chapterNumber: 2,
        title: "Network Layer & Subnetting",
        description: "IPv4 header structure, CIDR notation, subnet mask calculations, ARP, ICMP, and Distance Vector vs Link State routing.",
        notes: [
          {
            id: "note-cn-201",
            order: 1,
            title: "01. IPv4 Addressing & Subnetting Masterclass",
            summary: "Classful vs classless addressing, network address, broadcast address calculation, subnet mask masking, and Variable Length Subnet Masking (VLSM).",
            pages: 32,
            author: "Prof. R. K. Sharma",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-07",
          },
        ],
      },
    ],
  },
  {
    id: "sb-5",
    subjectName: "Advanced Machine Learning",
    code: "AI601",
    description: "Deep neural networks, backpropagation calculus, optimization techniques, CNNs, RNNs, and transformer models.",
    course: "M.Tech Computer Science & AI",
    level: "PG",
    chapters: [
      {
        id: "ch-ml-1",
        chapterNumber: 1,
        title: "Deep Neural Networks & Optimization",
        description: "Multilayer perceptrons, activation functions (ReLU, Sigmoid, Softmax), loss functions, and backpropagation calculus.",
        notes: [
          {
            id: "note-ml-101",
            order: 1,
            title: "01. Neural Network Foundations & Backprop Derivative Proofs",
            summary: "Mathematical derivation of chain rule in gradient backpropagation, weight initialization techniques (Xavier/He), and loss surfaces.",
            pages: 38,
            author: "Dr. K. Mehta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-04",
          },
          {
            id: "note-ml-102",
            order: 2,
            title: "02. Advanced Optimizers & Regularization",
            summary: "Comparison of SGD, Momentum, RMSProp, and Adam optimizers. Dropout, L1/L2 regularization, and batch normalization.",
            pages: 44,
            author: "Dr. K. Mehta",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-07",
          },
        ],
      },
    ],
  },
  {
    id: "sb-6",
    subjectName: "Thermodynamics & Heat Transfer",
    code: "ME301",
    description: "Zeroth, First, Second, and Third Laws of Thermodynamics, enthalpy, entropy, Carnot engine, and refrigeration cycles.",
    course: "B.Tech Mechanical Eng",
    level: "UG",
    chapters: [
      {
        id: "ch-thermo-1",
        chapterNumber: 1,
        title: "Laws of Thermodynamics & Carnot Engine",
        description: "Energy conservation equations, closed and open system analysis, entropy changes, and Carnot cycle efficiency calculations.",
        notes: [
          {
            id: "note-thermo-101",
            order: 1,
            title: "01. Zeroth & First Law Energy Balance Equations",
            summary: "Work and heat interaction, internal energy, enthalpy, Steady Flow Energy Equation (SFEE) applied to nozzles, turbines, and compressors.",
            pages: 26,
            author: "Prof. S. V. Nair",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-03",
          },
          {
            id: "note-thermo-102",
            order: 2,
            title: "02. Second Law, Entropy & Carnot Cycle Analysis",
            summary: "Kelvin-Planck and Clausius statements, Clausius inequality, reversible processes, and Carnot heat engine thermal efficiency derivations.",
            pages: 35,
            author: "Prof. S. V. Nair",
            url: "https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf",
            dateAdded: "2026-08-06",
          },
        ],
      },
    ],
  },
  ...csBtechSubjects,
  ...allCurriculums.flatMap(c => c.subjects)
];
